### ISSUE TITLE
Swagger-sails generates useless/strange routes

### ISSUE THREAD

**Issue by SkinyMonkey** [apigee-127/swagger-sails#5]
With a simple account model swagger-sails generate stuff like:

DELETE /account/find/{id}
GET /account/find/{id}
PATCH /account/find/{id}
POST /account/find/{id}
PUT /account/find/{id}

Is it a normal behaviour?

**Comment by theganyo** [comment]
Sorry, I don't understand. How are you getting those routes?

**Comment by adrien-candiotti** [comment]
Woops! My bad, i posted this issue in the wrong repo!

**Comment by theganyo** [comment]
No worries.
